### PR TITLE
Unit test additions + es6 data.js

### PR DESCRIPTION
**Pull request by ghost**
Removed Gulp + set up npm commands
Converted data.js to use es6
Replaced Chai with Should.js
Fixed line endings in various files I modified.
Started unit testing
Modified Travis config

### CODE REVIEW

**Comment by LiamKenneth** [comment]
Boom Coverage has gone up! Will check this now

**Comment by LiamKenneth** [comment]
λ npm test

tests go to run but error, see below, tried several time. is there something i'm missing? i did run npm install beforehand

```
> muddungeonjs@0.0.1 test C:\Users\Liam\Documents\Git Projects\MudDungeonJS
> istanbul cover ./node_modules/mocha/bin/_mocha spec/**/**/*

No coverage information was collected, exit without writing coverage information
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Liam\Documents\Git Projects\MudDungeonJS\spec\Game'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\mocha\lib\mocha.js:216:1
4)
    at Mocha.run (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\mocha\bin\_mocha:403:
18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\Liam\Documents\Git Projects\MudDungeon
JS\node_modules\istanbul\lib\hook.js:109:37)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at runFn (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\command\common\run-wi
th-cover.js:122:16)
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\command\common\run-with-cove
r.js:251:17
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\util\file-matcher.js:68:16
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\node_modules\async\lib\async.js:
52:16
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\node_modules\async\lib\async.js:
361:13
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\node_modules\async\lib\async.js:
52:16
    at done (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\node_modules\async\lib\asy
nc.js:246:17)
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\node_modules\async\lib\async.js:
44:16
    at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\node_modules\async\lib\async.js:
358:17
    at LOOP (fs.js:1534:14)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
 npm ERR! Test failed.  See above for more details.
```

**Comment by ghost** [comment]
Hmm, Windows eigh. I wonder if the forward slashes in packages.json are the issue. Does this make a difference:

`"test": "istanbul cover _mocha spec"`

**Comment by ghost** [comment]
This also works for me, need to install mocha globally for this:

`npm i -g mocha`
`istanbul cover _mocha spec/**/**/*`

**Comment by LiamKenneth** [comment]
Yeah no doubt a windows issue!

I get a new error with your change looks like mocha it's self is failing

```
 npm test                                                                                                                                                    

 muddungeonjs@0.0.1 test C:\Users\Liam\Documents\Git Projects\MudDungeonJS                                                                                   
 istanbul cover _mocha ./spec/**/**/*                                                                                                                        

o coverage information was collected, exit without writing coverage information                                                                              
:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\.bin\_mocha.CMD:1                                                                              
function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (                                                                    
                                                             ^                                                                                               

yntaxError: Unexpected token ILLEGAL                                                                                                                         
   at exports.runInThisContext (vm.js:53:16)                                                                                                                 
   at Module._compile (module.js:374:25)                                                                                                                     
   at Object.Module._extensions..js (module.js:417:10)                                                                                                       
   at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\hook.js:109:37)   
   at Module.load (module.js:344:32)                                                                                                                         
   at Function.Module._load (module.js:301:12)                                                                                                               
   at Function.Module.runMain (module.js:442:10)                                                                                                             
   at runFn (C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)                            
   at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17                                    
   at C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\istanbul\lib\util\file-matcher.js:68:16                                                 
npm ERR! Test failed.  See above for more details.                                                                                                           

```

**Comment by ghost** [comment]
Does the `npm run lint` also give you errors?
If so it's the forward slashes I need to investigate.

**Comment by LiamKenneth** [comment]
Yeah that worked! gave 4500+ lint errors! :-O

**Comment by ghost** [comment]
I tried something slightly different:
`istanbul cover mocha ./spec/**/**/*`

May also be worth trying `npm prune` to remove any packages not included inside package.json and updating mocha? I'll keep looking into it.

**Comment by LiamKenneth** [comment]
Tests ran fine on travis, I watched it! but on my machine it fails. tried `npm prune` It removed all the old gulp packages, re ran `npm install` then `npm test` but still errors

```
C:\Users\Liam\Documents\Git Projects\MudDungeonJS\node_modules\.bin\mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^

SyntaxError: Unexpected token ILLEGAL
```

**Comment by ghost** [comment]
What version of node are you using? I'm on `v5.6.0`

**Comment by LiamKenneth** [comment]
V4.2.6 I'll update, and see if it fixes it, EDIT: That, or I buy a mac / Switch to linux!

**Comment by ghost** [comment]
Cool. I'm also going to try creating an `index.js` inside the spec dir and point to that.

**Comment by LiamKenneth** [comment]
I updated, but still fails for me. will try again tomorrow have to go!

**Comment by LiamKenneth** [comment]
Got it! change mocha to ./node_modules/mocha/bin/_mocha

http://stackoverflow.com/a/35559698

Now it works

**Comment by ghost** [comment]
Awesome :+1: 
I'll make that change and remove spec.js

**Comment by LiamKenneth** [comment]
Thanks, still need spec.js I think, I changed it to this 

`"test": "istanbul cover ./node_modules/mocha/bin/_mocha spec.js",`

**Comment by ghost** [comment]
Ok cool. I called it `index.js`, moved into the spec dir and now have:
`istanbul cover ./node_modules/mocha/bin/_mocha spec`

**Comment by LiamKenneth** [comment]
Boom all working, thanks! :+1:

**Pull request merged**
